/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) cartpole_learned_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {1, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};

/* External functions */
int residual_pendulum(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);


/* residual_pendulum:(i0[1x5])->(o0[1x2]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  if (residual_pendulum(arg, res, iw, w, mem)) return 1;
  return 0;
}

/* cartpole_learned_expl_ode_fun:(i0[4],i1,i2[0])->(o0[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+1, *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09;
  casadi_real w10, w11, w12, *w13=w+13, *w14=w+17, *w15=w+22, *w16=w+24;
  const casadi_real **arg1=arg+3, *cs;
  /* #0: @0 = input[0][1] */
  w00 = arg[0] ? arg[0][1] : 0;
  /* #1: @1 = input[1][0] */
  w01 = arg[1] ? arg[1][0] : 0;
  /* #2: @2 = 0.02178 */
  w02 = 2.1780000000000001e-02;
  /* #3: @3 = input[0][3] */
  w03 = arg[0] ? arg[0][3] : 0;
  /* #4: @4 = sq(@3) */
  w04 = casadi_sq( w03 );
  /* #5: @4 = (@2*@4) */
  w04  = (w02*w04);
  /* #6: @5 = input[0][2] */
  w05 = arg[0] ? arg[0][2] : 0;
  /* #7: @6 = sin(@5) */
  w06 = sin( w05 );
  /* #8: @4 = (@4*@6) */
  w04 *= w06;
  /* #9: @4 = (@1+@4) */
  w04  = (w01+w04);
  /* #10: @7 = 0.726 */
  w07 = 7.2599999999999998e-01;
  /* #11: @4 = (@4/@7) */
  w04 /= w07;
  /* #12: @8 = 9.8 */
  w08 = 9.8000000000000007e+00;
  /* #13: @8 = (@8*@6) */
  w08 *= w06;
  /* #14: @6 = cos(@5) */
  w06 = cos( w05 );
  /* #15: @9 = (@6*@4) */
  w09  = (w06*w04);
  /* #16: @8 = (@8-@9) */
  w08 -= w09;
  /* #17: @9 = 0.33 */
  w09 = 3.3000000000000002e-01;
  /* #18: @10 = 1.33333 */
  w10 = 1.3333333333333333e+00;
  /* #19: @11 = 0.066 */
  w11 = 6.6000000000000003e-02;
  /* #20: @12 = sq(@6) */
  w12 = casadi_sq( w06 );
  /* #21: @11 = (@11*@12) */
  w11 *= w12;
  /* #22: @11 = (@11/@7) */
  w11 /= w07;
  /* #23: @10 = (@10-@11) */
  w10 -= w11;
  /* #24: @9 = (@9*@10) */
  w09 *= w10;
  /* #25: @8 = (@8/@9) */
  w08 /= w09;
  /* #26: @2 = (@2*@8) */
  w02 *= w08;
  /* #27: @2 = (@2*@6) */
  w02 *= w06;
  /* #28: @2 = (@2/@7) */
  w02 /= w07;
  /* #29: @4 = (@4-@2) */
  w04 -= w02;
  /* #30: @13 = vertcat(@0, @4, @3, @8) */
  rr=w13;
  *rr++ = w00;
  *rr++ = w04;
  *rr++ = w03;
  *rr++ = w08;
  /* #31: @4 = 0 */
  w04 = 0.;
  /* #32: @8 = input[0][0] */
  w08 = arg[0] ? arg[0][0] : 0;
  /* #33: @14 = vertcat(@8, @0, @5, @3, @1) */
  rr=w14;
  *rr++ = w08;
  *rr++ = w00;
  *rr++ = w05;
  *rr++ = w03;
  *rr++ = w01;
  /* #34: @14 = @14' */
  /* #35: @15 = residual_pendulum(@14) */
  arg1[0]=w14;
  res1[0]=w15;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #36: @15 = @15' */
  /* #37: @8 = @15[0] */
  for (rr=(&w08), cs=w15+0; cs!=w15+1; cs+=1) *rr++ = *cs;
  /* #38: @0 = @15[1] */
  for (rr=(&w00), cs=w15+1; cs!=w15+2; cs+=1) *rr++ = *cs;
  /* #39: @16 = vertcat(@4, @8, @4, @0) */
  rr=w16;
  *rr++ = w04;
  *rr++ = w08;
  *rr++ = w04;
  *rr++ = w00;
  /* #40: @13 = (@13+@16) */
  for (i=0, rr=w13, cs=w16; i<4; ++i) (*rr++) += (*cs++);
  /* #41: output[0][0] = @13 */
  casadi_copy(w13, 4, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_learned_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int cartpole_learned_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_learned_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cartpole_learned_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int cartpole_learned_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void cartpole_learned_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void cartpole_learned_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void cartpole_learned_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int cartpole_learned_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int cartpole_learned_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real cartpole_learned_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cartpole_learned_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* cartpole_learned_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cartpole_learned_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* cartpole_learned_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int cartpole_learned_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 28;
  return 0;
}

CASADI_SYMBOL_EXPORT int cartpole_learned_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 28*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
